site_name: Services
site_url: https://manuales.algoritmia.sv/services/
site_description: Manual de usuario de Servicios
site_author: Edwin Fajardo
copyright: Copyright &copy;2024 Algoritmia SV
site_dir: /store/bphp/manuals/services
nav:
  - Inicio: index.md
  - Usuario: usuario.md
  - Suministro:
    - 'Usuarios de servicios': suministro/usuarios.md
    - Acometidas: suministro/acometidas.md
    - Facturación: suministro/facturacion.md
    - Lecturas: suministro/lecturas.md
    - Cobros: suministro/cobros.md
    - Sectores: suministro/sectores.md
  - Herramientas:
    - 'Historial de actividades': herramientas/historial-actividades.md
    - 'Papelera de reciclaje': herramientas/papelera.md
  - Configuraciones:
    - 'Datos de la empresa': configuraciones/entidad.md
    - Preferencias: configuraciones/preferencias.md
    - 'Cuentas bancarias': configuraciones/cuentas-bancarias.md
    - 'Planes tarifarios': configuraciones/planes-tarifarios.md
    - Roles: configuraciones/roles.md
    - Usuarios: configuraciones/usuarios.md
theme:
  name: mkdocs
  nav_style: dark
  locale: es
extra_css:
  - css/algoritmiasv.css
markdown_extensions:
  - attr_list
